ktor:
  deployment:
    port: 8080
  application:
    modules:
        - com.reza.plugins.SerializationKt.configureSerialization
        - com.reza.plugins.DependencyInjectionKt.configureDependencyInjection
        - com.reza.plugins.DatabaseKt.configureDatabase
        - com.reza.plugins.SecurityKt.configureSecurity
        - com.reza.plugins.RoutingKt.configureRouting
