ktor:
  deployment:
    port: 8080
  application:
    modules:
        - com.reza.plugins.SerializationKt.configureSerialization
        - com.reza.plugins.DependencyInjectionKt.configureDependencyInjection
        - com.reza.plugins.DatabaseKt.configureDatabase
        - com.reza.plugins.SecurityKt.configureSecurity
        - com.reza.plugins.RoutingKt.configureRouting

jwt:
  secret: "${JWT_SECRET:my-super-secret-local-dev-key-12345}"
  issuer: "com.reza.shopping"

database:
  driver: "${DB_DRIVER:org.postgresql.Driver}"
  url: "${DB_URL:jdbc:postgresql://localhost:5432/shopping_db}"
  user: "${DB_USER:postgres}"
  password: "${DB_PASSWORD:your_password}"